title: "Ivan Grishaev's blog"
email: ivan@grishaev.me
description: >
  Writing on programming, education, books and negotiations.
baseurl: ""
lang: ru
url: "https://grishaev.me"

url_github: "https://github.com/igrishaev"
url_telegram: "tg://resolve?domain=igrishaev_blog"
url_linkedin: "https://www.linkedin.com/in/igrishaev"

url_gumroad_clj_prod_ru: "https://gum.co/clojure-in-prod"
url_s3_static: "https://s3.amazonaws.com/igrishaev.public"

url_dobrofile_clj_prod_ru: "https://dobrofile.ru/?s=c2f86cd04"

clj_prod_book_price: 1000
clj_prod_book_dmk: 'https://dmkpress.com/catalog/computer/programming/functional/978-5-93700-055-2/'
clj_prod_book_ridero: 'https://ridero.ru/books/clojure_na_proizvodstve/'
clj_prod_book_ozon: 'https://www.ozon.ru/product/clojure-na-proizvodstve-179829229/'
clj_prod_book_ali: 'https://aliexpress.ru/item/1005002322504648.html'
clj_prod_book_bookvoed: 'https://www.bookvoed.ru/book?id=10490030'
clj_prod_book_chitai_gorod: 'https://www.chitai-gorod.ru/catalog/book/1267534/'
clj_prod_book_wildberries: 'https://www.wildberries.ru/catalog/35868853/detail.aspx'


author: Ivan Grishaev
paginate: 10
markdown: kramdown

future: true

plugins:
  - kramdown
  - rouge
  - jekyll-watch
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll/tagging
  - jekyll-sitemap
  - stringex

exclude:
  - aws
  - gh-pages
  - instantview
  - scripts
  - todo.org
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Makefile
  - clj-comments

host: 0.0.0.0
port: 4001

comment_path: "https://functions.yandexcloud.net/d4ehfuf08fjfjr59ivnf"

tag_page_layout: tag_page
tag_page_dir: tag

tag_permalink_style: pretty

kramdown:
  auto_ids: true
  auto_id_stripping: true
  transliterated_header_ids: true

collections:
  posts:
    output: true
  comments:
    output: false
